# Generated by Django 3.0.3 on 2020-04-17 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_title', models.CharField(max_length=128)),
                ('book_author', models.CharField(max_length=128)),
                ('book_link', models.URLField(blank=True, max_length=512, null=True)),
            ],
        ),
    ]
