# Generated by Django 3.0.3 on 2020-04-14 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_type',
            field=models.CharField(choices=[('Essay', 'Essay'), ('New Thought', 'New Thought')], default='Essay', max_length=15),
        ),
    ]
